micronaut:
  application:
    name: micronaut-db-benchmark
datasources:
  default:
    url: '${JDBC_URL}'
    username: '${DB_USERNAME}'
    password: '${DB_PASSWORD}'
    dialect: '${SQL_DIALECT}'
    driverClassName: '${DB_DRIVER}'
jpa:
  default:
    properties:
      hibernate:
        generate_statistics: true
#        show_sql: true
