micronaut:
  application:
    name: micronaut-db-benchmark
datasources:
  default:
    url: 'jdbc:holodb:embedded:resource://holodb.yaml?schema=university'
    #url: 'jdbc:h2:mem:devDb;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE'
    username: 'sa'
    password: ''
    dialect: 'H2'
    #dialect: 'H2'
    driverClassName: 'hu.webarticum.holodb.embedded.HoloEmbeddedDriver'
    #driverClassName: 'org.h2.Driver'
jpa:
  default:
    properties:
      hibernate:
        generate_statistics: true
